Repository jsac2001/Votissimo, pull requests merged in 2025-02, with the labels that each got.

#1 Ajout fonctionnalité logout
  composer.lock
  public/index.php
  public/logout.php
Labels: enhancement

#2 Bug FIx Create scrutin db
  public/create_scrutin.php
Labels: bug

#4 New Features
  public/admin.php
  public/delete_scrutin.php
  public/resultat_scrutin.php
  public/results.php
  src/calcul_resultats.php
Labels: bug, enhancement

#5 New feature
  public/resultat_scrutin.php
  public/vote.php
Labels: enhancement

#6 New feature
  public/admin.php
  public/index.php
  public/notification.php
  public/resultat_scrutin.php
  public/results.php
Labels: enhancement

#7 New feature Website statistics
  public/admin.php
Labels: enhancement

#8 New style
  public/admin.php
  public/assets/admin.css
  public/assets/auth.css
  public/assets/create_scrutin.css
  public/assets/header.css
  public/assets/index.css
  public/assets/login.css
  public/assets/vote.css
  public/auth.php
  public/create_scrutin.php
  public/index.php
  public/login.php
  public/template/header.php
  public/vote.php
Labels: enhancement
